CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[Name] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(100) NOT NULL,
	[RegistrationDate] Datetime NOT NULL,
)
