-- Genre
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Rock', 'Rock and Roll is a form of rock music developed in the 1950s and 1960s. Rock music combines many kinds of music from the United States, such as country music, folk music, church music, work songs, blues and jazz.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Jazz', 'Jazz is a type of music which was invented in the United States. Jazz music combines African-American music with European music. Some common jazz instruments include the saxophone, trumpet, piano, double bass, and drums.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Metal', 'Heavy Metal is a loud, aggressive style of Rock music. The bands who play heavy-metal music usually have one or two guitars, a bass guitar and drums. In some bands, electronic keyboards, organs, or other instruments are used. Heavy metal songs are loud and powerful-sounding, and have strong rhythms that are repeated. There are many different types of Heavy Metal, some of which are described below. Heavy metal bands sometimes dress in jeans, leather jackets, and leather boots, and have long hair. Heavy metal bands sometimes behave in a dramatic way when they play their instruments or sing. However, many heavy metal bands do not like to do this.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Alternative', 'Alternative rock is a type of rock music that became popular in the 1980s and became widely popular in the 1990s. Alternative rock is made up of various subgenres that have come out of the indie music scene since the 1980s, such as grunge, indie rock, Britpop, gothic rock, and indie pop. These genres are sorted by their collective types of punk, which laid the groundwork for alternative music in the 1970s.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Disco', 'Disco is a style of pop music that was popular in the mid-1970s. Disco music has a strong beat that people can dance to. People usually dance to disco music at bars called disco clubs. The word "disco" is also used to refer to the style of dancing that people do to disco music, or to the style of clothes that people wear to go disco dancing. Disco was at its most popular in the United States and Europe in the 1970s and early 1980s. Disco was brought into the mainstream by the hit movie Saturday Night Fever, which was released in 1977. This movie, which starred John Travolta, showed people doing disco dancing. Many radio stations played disco in the late 1970s.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Blues', 'The blues is a form of music that started in the United States during the start of the 20th century. It was started by former African slaves from spirituals, praise songs, and chants. The first blues songs were called Delta blues. These songs came from the area near the mouth of the Mississippi River.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Latin', 'Latin American music is the music of all countries in Latin America (and the Caribbean) and comes in many varieties. Latin America is home to musical styles such as the simple, rural conjunto music of northern Mexico, the sophisticated habanera of Cuba, the rhythmic sounds of the Puerto Rican plena, the symphonies of Heitor Villa-Lobos, and the simple and moving Andean flute. Music has played an important part recently in Latin America''s politics, the nueva canción movement being a prime example. Latin music is very diverse, with the only truly unifying thread being the use of Latin-derived languages, predominantly the Spanish language, the Portuguese language in Brazil, and to a lesser extent, Latin-derived creole languages, such as those found in Haiti.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Reggae', 'Reggae is a music genre first developed in Jamaica in the late 1960s. While sometimes used in a broader sense to refer to most types of Jamaican music, the term reggae more properly denotes a particular music style that originated following on the development of ska and rocksteady.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Pop', 'Pop music is a music genre that developed from the mid-1950s as a softer alternative to rock ''n'' roll and later to rock music. It has a focus on commercial recording, often oriented towards a youth market, usually through the medium of relatively short and simple love songs. While these basic elements of the genre have remained fairly constant, pop music has absorbed influences from most other forms of popular music, particularly borrowing from the development of rock music, and utilizing key technological innovations to produce new variations on existing themes.')
INSERT INTO [dbo].[Genre]([Name], [Description]) VALUES('Classical', 'Classical music is a very general term which normally refers to the standard music of countries in the Western world. It is music that has been composed by musicians who are trained in the art of writing music (composing) and written down in music notation so that other musicians can play it. Classical music can also be described as "art music" because great art (skill) is needed to compose it and to perform it well. Classical music differs from pop music because it is not made just in order to be popular for a short time or just to be a commercial success.')

-- Artist
INSERT INTO [dbo].[Artist]([Name]) VALUES('Aaron Copland & London Symphony Orchestra')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Aaron Goldberg')
INSERT INTO [dbo].[Artist]([Name]) VALUES('AC/DC')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Accept')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Adrian Leaper & Doreen de Feis')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Aerosmith')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Aisha Duo')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Alanis Morissette')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Alberto Turco & Nova Schola Gregoriana')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Alice In Chains')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Amy Winehouse')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Anita Ward')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Antônio Carlos Jobim')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Apocalyptica')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Audioslave')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Barry Wordsworth & BBC Concert Orchestra')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Berliner Philharmoniker & Hans Rosbaud')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Berliner Philharmoniker & Herbert Von Karajan')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Billy Cobham')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Black Label Society')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Black Sabbath')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Boston Symphony Orchestra & Seiji Ozawa')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Britten Sinfonia, Ivor Bolton & Lesley Garrett')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Bruce Dickinson')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Buddy Guy')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Caetano Veloso')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Cake')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Calexico')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Cássia Eller')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Chic')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Chicago Symphony Orchestra & Fritz Reiner')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Chico Buarque')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Chico Science & Nação Zumbi')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Choir Of Westminster Abbey & Simon Preston')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Chris Cornell')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Christopher O''Riley')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Cidade Negra')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Cláudio Zoli')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Creedence Clearwater Revival')
INSERT INTO [dbo].[Artist]([Name]) VALUES('David Coverdale')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Deep Purple')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Dennis Chambers')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Djavan')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Donna Summer')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Dread Zeppelin')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Ed Motta')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Edo de Waart & San Francisco Symphony')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Elis Regina')
INSERT INTO [dbo].[Artist]([Name]) VALUES('English Concert & Trevor Pinnock')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Eric Clapton')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Eugene Ormandy')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Faith No More')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Falamansa')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Foo Fighters')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Frank Zappa & Captain Beefheart')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Fretwork')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Funk Como Le Gusta')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Gerald Moore')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Gilberto Gil')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Godsmack')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Gonzaguinha')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Göteborgs Symfoniker & Neeme Järvi')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Guns N'' Roses')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Gustav Mahler')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Incognito')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Iron Maiden')
INSERT INTO [dbo].[Artist]([Name]) VALUES('James Levine')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Jamiroquai')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Jimi Hendrix')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Joe Satriani')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Jorge Ben')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Jota Quest')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Judas Priest')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Julian Bream')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Kent Nagano and Orchestre de l''Opéra de Lyon')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Kiss')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Led Zeppelin')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Legião Urbana')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Lenny Kravitz')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Les Arts Florissants & William Christie')
INSERT INTO [dbo].[Artist]([Name]) VALUES('London Symphony Orchestra & Sir Charles Mackerras')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Luciana Souza/Romero Lubambo')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Lulu Santos')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Marcos Valle')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Marillion')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Marisa Monte')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Martin Roscoe')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Maurizio Pollini')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Mela Tenenbau, Pro Musica Prague & Richard Kapp')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Men At Work')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Metallica')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Michael Tilson Thomas & San Francisco Symphony')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Miles Davis')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Milton Nascimento')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Mötley Crüe')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Motörhead')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Nash Ensemble')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Nicolaus Esterhazy Sinfonia')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Nirvana')
INSERT INTO [dbo].[Artist]([Name]) VALUES('O Terço')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Olodum')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Orchestra of The Age of Enlightenment')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Os Paralamas Do Sucesso')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Ozzy Osbourne')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Page & Plant')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Paul D''Ianno')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Pearl Jam')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Pink Floyd')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Queen')
INSERT INTO [dbo].[Artist]([Name]) VALUES('R.E.M.')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Raul Seixas')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Red Hot Chili Peppers')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Roger Norrington, London Classical Players')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Royal Philharmonic Orchestra & Sir Thomas Beecham')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Rush')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Santana')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Scholars Baroque Ensemble')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Scorpions')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Sergei Prokofiev & Yuri Temirkanov')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Sir Georg Solti & Wiener Philharmoniker')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Skank')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Soundgarden')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Spyro Gyra')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Stevie Ray Vaughan & Double Trouble')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Stone Temple Pilots')
INSERT INTO [dbo].[Artist]([Name]) VALUES('System Of A Down')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Temple of the Dog')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Terry Bozzio, Tony Levin & Steve Stevens')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The 12 Cellists of The Berlin Philharmonic')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The Black Crowes')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The Cult')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The Doors')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The King''s Singers')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The Police')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The Posies')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The Rolling Stones')
INSERT INTO [dbo].[Artist]([Name]) VALUES('The Who')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Tim Maia')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Ton Koopman')
INSERT INTO [dbo].[Artist]([Name]) VALUES('U2')
INSERT INTO [dbo].[Artist]([Name]) VALUES('UB40')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Van Halen')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Various Artists')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Velvet Revolver')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Vinícius De Moraes')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Wilhelm Kempff')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Yehudi Menuhin')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Yo-Yo Ma')
INSERT INTO [dbo].[Artist]([Name]) VALUES('Zeca Pagodinho')

-- Album
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Best Of Men At Work', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Men At Work'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('A Copland Celebration, Vol. I', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Aaron Copland & London Symphony Orchestra'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Worlds', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Aaron Goldberg'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('For Those About To Rock We Salute You', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'AC/DC'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Let There Be Rock', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'AC/DC'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Balls to the Wall', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Accept'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Restless and Wild', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Accept'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Górecki: Symphony No. 3', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Adrian Leaper & Doreen de Feis'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Big Ones', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Aerosmith'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Quiet Songs', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Aisha Duo'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Jagged Little Pill', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Alanis Morissette'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Facelift', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Alice In Chains'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Frank', (select GenreId from Genre where Name = 'Pop'),8.99, (select ArtistId from Artist where Name = 'Amy Winehouse'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Ring My Bell', (select GenreId from Genre where Name = 'Disco'),8.99, (select ArtistId from Artist where Name = 'Anita Ward'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Chill: Brazil (Disc 2)', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Antônio Carlos Jobim'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Warner 25 Anos', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Antônio Carlos Jobim'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Plays Metallica By Four Cellos', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Apocalyptica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Revelations', (select GenreId from Genre where Name = 'Alternative'),8.99, (select ArtistId from Artist where Name = 'Audioslave'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Audioslave', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Audioslave'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Last Night of the Proms', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Barry Wordsworth & BBC Concert Orchestra'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Sibelius: Finlandia', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Berliner Philharmoniker & Hans Rosbaud'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Mozart: Symphonies Nos. 40 & 41', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Berliner Philharmoniker & Herbert Von Karajan'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Best Of Billy Cobham', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Billy Cobham'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Alcohol Fueled Brewtality Live! [Disc 1]', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Black Label Society'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Alcohol Fueled Brewtality Live! [Disc 2]', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Black Label Society'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Black Sabbath Vol. 4 (Remaster)', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Black Sabbath'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Black Sabbath', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Black Sabbath'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Carmina Burana', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Boston Symphony Orchestra & Seiji Ozawa'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('A Soprano Inspired', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Britten Sinfonia, Ivor Bolton & Lesley Garrett'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Chemical Wedding', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Bruce Dickinson'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Prenda Minha', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Caetano Veloso'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Sozinho Remix Ao Vivo', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Caetano Veloso'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Cake: B-Sides and Rarities', (select GenreId from Genre where Name = 'Alternative'),8.99, (select ArtistId from Artist where Name = 'Cake'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Carried to Dust (Bonus Track Version)', (select GenreId from Genre where Name = 'Alternative'),8.99, (select ArtistId from Artist where Name = 'Calexico'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Cássia Eller - Sem Limite [Disc 1]', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Cássia Eller'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Le Freak', (select GenreId from Genre where Name = 'Disco'),8.99, (select ArtistId from Artist where Name = 'Chic'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Scheherazade', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Chicago Symphony Orchestra & Fritz Reiner'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Minha Historia', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Chico Buarque'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Afrociberdelia', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Chico Science & Nação Zumbi'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Da Lama Ao Caos', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Chico Science & Nação Zumbi'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Carry On', (select GenreId from Genre where Name = 'Alternative'),8.99, (select ArtistId from Artist where Name = 'Chris Cornell'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('SCRIABIN: Vers la flamme', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Christopher O''Riley'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Acústico MTV [Live]', (select GenreId from Genre where Name = 'Reggae'),8.99, (select ArtistId from Artist where Name = 'Cidade Negra'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Cidade Negra - Hits', (select GenreId from Genre where Name = 'Reggae'),8.99, (select ArtistId from Artist where Name = 'Cidade Negra'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Na Pista', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Cláudio Zoli'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Chronicle, Vol. 1', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Creedence Clearwater Revival'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Chronicle, Vol. 2', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Creedence Clearwater Revival'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Into The Light', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'David Coverdale'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Come Taste The Band', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Deep Purple In Rock', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Fireball', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Machine Head', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('MK III The Final Concerts [Disc 1]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Purpendicular', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Slaves And Masters', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Stormbringer', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Battle Rages On', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Final Concerts (Disc 2)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Deep Purple'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Outbreak', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Dennis Chambers'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Djavan Ao Vivo - Vol. 02', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Djavan'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Djavan Ao Vivo - Vol. 1', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Djavan'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('MacArthur Park Suite', (select GenreId from Genre where Name = 'Disco'),8.99, (select ArtistId from Artist where Name = 'Donna Summer'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Un-Led-Ed', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Dread Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Best of Ed Motta', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Ed Motta'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Adams, John: The Chairman Dances', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Edo de Waart & San Francisco Symphony'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Elis Regina-Minha História', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Elis Regina'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Pachelbel: Canon & Gigue', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'English Concert & Trevor Pinnock'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Unplugged', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Eric Clapton'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Cream Of Clapton', (select GenreId from Genre where Name = 'Blues'),8.99, (select ArtistId from Artist where Name = 'Eric Clapton'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Unplugged', (select GenreId from Genre where Name = 'Blues'),8.99, (select ArtistId from Artist where Name = 'Eric Clapton'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Respighi:Pines of Rome', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Eugene Ormandy'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Strauss: Waltzes', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Eugene Ormandy'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('King For A Day Fool For A Lifetime', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Faith No More'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Deixa Entrar', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Falamansa'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('In Your Honor [Disc 1]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Foo Fighters'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('In Your Honor [Disc 2]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Foo Fighters'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Colour And The Shape', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Foo Fighters'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Bongo Fury', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Frank Zappa & Captain Beefheart'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Roda De Funk', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Funk Como Le Gusta'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Quanta Gente Veio Ver (Live)', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Gilberto Gil'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Quanta Gente Veio ver--Bônus De Carnaval', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Gilberto Gil'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Faceless', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Godsmack'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Meus Momentos', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Gonzaguinha'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Nielsen: The Six Symphonies', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Göteborgs Symfoniker & Neeme Järvi'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Appetite for Destruction', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Guns N'' Roses'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Use Your Illusion I', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Guns N'' Roses'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Use Your Illusion II', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Guns N'' Roses'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Blue Moods', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Incognito'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('A Matter of Life and Death', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Brave New World', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Fear Of The Dark', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Live At Donington 1992 (Disc 1)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Live At Donington 1992 (Disc 2)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Rock In Rio [CD2]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Number of The Beast', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The X Factor', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Virtual XI', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('A Real Dead One', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('A Real Live One', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Live After Death', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('No Prayer For The Dying', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Piece Of Mind', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Powerslave', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Rock In Rio [CD1]', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Rock In Rio [CD2]', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Seventh Son of a Seventh Son', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Somewhere in Time', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Number of The Beast', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Iron Maiden', (select GenreId from Genre where Name = 'Blues'),8.99, (select ArtistId from Artist where Name = 'Iron Maiden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Mascagni: Cavalleria Rusticana', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'James Levine'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Emergency On Planet Earth', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Jamiroquai'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Are You Experienced?', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Jimi Hendrix'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Surfing with the Alien (Remastered)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Joe Satriani'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Jorge Ben Jor 25 Anos', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Jorge Ben'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Jota Quest-1995', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Jota Quest'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Living After Midnight', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Judas Priest'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Weill: The Seven Deadly Sins', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Kent Nagano and Orchestre de l''Opéra de Lyon'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Greatest Kiss', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Kiss'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Unplugged [Live]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Kiss'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('BBC Sessions [Disc 1] [Live]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('BBC Sessions [Disc 2] [Live]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Coda', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Houses Of The Holy', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('In Through The Out Door', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('IV', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Led Zeppelin I', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Led Zeppelin II', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Led Zeppelin III', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Physical Graffiti [Disc 1]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Physical Graffiti [Disc 2]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Presence', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Song Remains The Same (Disc 1)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Song Remains The Same (Disc 2)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Led Zeppelin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Mais Do Mesmo', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Legião Urbana'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Greatest Hits', (select GenreId from Genre where Name = 'Reggae'),8.99, (select ArtistId from Artist where Name = 'Lenny Kravitz'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Greatest Hits', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Lenny Kravitz'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Greatest Hits', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Lenny Kravitz'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Tchaikovsky: The Nutcracker', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'London Symphony Orchestra & Sir Charles Mackerras'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Duos II', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Luciana Souza/Romero Lubambo'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Chill: Brazil (Disc 1)', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Marcos Valle'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Misplaced Childhood', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Marillion'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Barulhinho Bom', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Marisa Monte'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Szymanowski: Piano Works, Vol. 1', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Martin Roscoe'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('...And Justice For All', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Black Album', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Garage Inc. (Disc 1)', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Garage Inc. (Disc 2)', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Load', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Master Of Puppets', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('ReLoad', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Ride The Lightning', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('St. Anger', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Metallica'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Berlioz: Symphonie Fantastique', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Michael Tilson Thomas & San Francisco Symphony'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Prokofiev: Romeo & Juliet', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Michael Tilson Thomas & San Francisco Symphony'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Miles Ahead', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Miles Davis'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Essential Miles Davis [Disc 1]', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Miles Davis'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Essential Miles Davis [Disc 2]', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Miles Davis'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Milton Nascimento Ao Vivo', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Milton Nascimento'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Minas', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Milton Nascimento'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Motley Crue Greatest Hits', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Mötley Crüe'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Ace Of Spades', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Motörhead'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Mozart: Chamber Music', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Nash Ensemble'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Best of Beethoven', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Nicolaus Esterhazy Sinfonia'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Nevermind', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Nirvana'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Compositores', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'O Terço'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Olodum', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Olodum'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Bach: The Brandenburg Concertos', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Orchestra of The Age of Enlightenment'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Acústico MTV', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Os Paralamas Do Sucesso'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Arquivo II', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Os Paralamas Do Sucesso'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Arquivo Os Paralamas Do Sucesso', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Os Paralamas Do Sucesso'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Tribute', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'Ozzy Osbourne'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Bark at the Moon (Remastered)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Ozzy Osbourne'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Blizzard of Ozz', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Ozzy Osbourne'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Diary of a Madman (Remastered)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Ozzy Osbourne'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('No More Tears (Remastered)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Ozzy Osbourne'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Speak of the Devil', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Ozzy Osbourne'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Walking Into Clarksdale', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Page & Plant'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Beast Live', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Paul D''Ianno'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Live On Two Legs [Live]', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Pearl Jam'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Riot Act', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Pearl Jam'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Ten', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Pearl Jam'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Vs.', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Pearl Jam'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Dark Side Of The Moon', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Pink Floyd'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Greatest Hits I', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Queen'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Greatest Hits II', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Queen'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('News Of The World', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Queen'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('New Adventures In Hi-Fi', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'R.E.M.'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Raul Seixas', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Raul Seixas'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('By The Way', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Red Hot Chili Peppers'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Californication', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Red Hot Chili Peppers'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Purcell: The Fairy Queen', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Roger Norrington, London Classical Players'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Haydn: Symphonies 99 - 104', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Royal Philharmonic Orchestra & Sir Thomas Beecham'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Retrospective I (1974-1980)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Rush'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Santana - As Years Go By', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Santana'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Santana Live', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Santana'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Supernatural', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Santana'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Handel: The Messiah (Highlights)', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Scholars Baroque Ensemble'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Prokofiev: Symphony No.1', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Sergei Prokofiev & Yuri Temirkanov'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Wagner: Favourite Overtures', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Sir Georg Solti & Wiener Philharmoniker'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Maquinarama', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Skank'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('O Samba Poconé', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Skank'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('A-Sides', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Soundgarden'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Heart of the Night', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Spyro Gyra'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Morning Dance', (select GenreId from Genre where Name = 'Jazz'),8.99, (select ArtistId from Artist where Name = 'Spyro Gyra'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('In Step', (select GenreId from Genre where Name = 'Blues'),8.99, (select ArtistId from Artist where Name = 'Stevie Ray Vaughan & Double Trouble'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Core', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Stone Temple Pilots'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Mezmerize', (select GenreId from Genre where Name = 'Metal'),8.99, (select ArtistId from Artist where Name = 'System Of A Down'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Temple of the Dog', (select GenreId from Genre where Name = 'Alternative'),8.99, (select ArtistId from Artist where Name = 'Temple of the Dog'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('[1997] Black Light Syndrome', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Terry Bozzio, Tony Levin & Steve Stevens'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('South American Getaway', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'The 12 Cellists of The Berlin Philharmonic'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Live [Disc 1]', (select GenreId from Genre where Name = 'Blues'),8.99, (select ArtistId from Artist where Name = 'The Black Crowes'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Live [Disc 2]', (select GenreId from Genre where Name = 'Blues'),8.99, (select ArtistId from Artist where Name = 'The Black Crowes'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Beyond Good And Evil', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'The Cult'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Doors', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'The Doors'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('English Renaissance', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'The King''s Singers'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Police Greatest Hits', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'The Police'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Every Kind of Light', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'The Posies'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Hot Rocks, 1964-1971 (Disc 1)', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'The Rolling Stones'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('No Security', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'The Rolling Stones'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Voodoo Lounge', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'The Rolling Stones'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('My Generation - The Very Best Of The Who', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'The Who'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Serie Sem Limite (Disc 1)', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Tim Maia'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Serie Sem Limite (Disc 2)', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Tim Maia'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Bach: Toccata & Fugue in D Minor', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Ton Koopman'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Achtung Baby', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'U2'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('B-Sides 1980-1990', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'U2'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('How To Dismantle An Atomic Bomb', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'U2'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Pop', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'U2'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Rattle And Hum', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'U2'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Best Of 1980-1990', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'U2'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('War', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'U2'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Zooropa', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'U2'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('UB40 The Best Of - Volume Two [UK]', (select GenreId from Genre where Name = 'Reggae'),8.99, (select ArtistId from Artist where Name = 'UB40'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Diver Down', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Van Halen'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('The Best Of Van Halen, Vol. I', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Van Halen'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Van Halen III', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Van Halen'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Van Halen', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Van Halen'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Axé Bahia 2001', (select GenreId from Genre where Name = 'Pop'),8.99, (select ArtistId from Artist where Name = 'Various Artists'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Sambas De Enredo 2001', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Various Artists'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Vozes do MPB', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Various Artists'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Contraband', (select GenreId from Genre where Name = 'Rock'),8.99, (select ArtistId from Artist where Name = 'Velvet Revolver'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Vinicius De Moraes', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Vinícius De Moraes'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Bach: Goldberg Variations', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Wilhelm Kempff'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Bartok: Violin & Viola Concertos', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Yehudi Menuhin'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Bach: The Cello Suites', (select GenreId from Genre where Name = 'Classical'),8.99, (select ArtistId from Artist where Name = 'Yo-Yo Ma'), '/Content/Images/placeholder.gif')
INSERT INTO [dbo].[Album]([Title], [GenreId], [Price], [ArtistId], [AlbumArtUrl]) VALUES('Ao Vivo [IMPORT]', (select GenreId from Genre where Name = 'Latin'),8.99, (select ArtistId from Artist where Name = 'Zeca Pagodinho'), '/Content/Images/placeholder.gif')


-- User
INSERT INTO [dbo].[User]([Name],[Email],[Password],[RegistrationDate]) VALUES('Jon Snow','admin@admin.com', '000102030405060708090A0B0C0D0E0F', '2019-08-16') -- password admin

